# The login screen: greetd starts a small niri session as the `greeter` user,
# which shows a wallpaper (swaybg) and gtkgreet on top of it.
#
# Why a package instead of home-manager: the greeter runs before anyone is
# logged in, as a different user, and /home/<user> is mode 0700 — so it cannot
# read anything from this repo or from $HOME. Everything it needs is therefore
# built here and installed into the *system* nix profile
# (/nix/var/nix/profiles/default) by scripts/setup_login.sh, which is
# world-readable and GC-safe.
{
  pkgs,
  ...
}:
let
  # Which wallpaper the login screen shows. Change this path and re-run
  # `sudo ./scripts/setup_login.sh` to pick another one.
  wallpaper = ../assets/wallpapers/golden-ratio/beautful_lake.jpg;

  # gtkgreet stylesheet (catppuccin mocha).
  css = ./greeter.css;
in
pkgs.runCommand "rei-login" { } ''
  mkdir -p $out/share/rei-login
  cp ${css} $out/share/rei-login/greeter.css
  cp ${wallpaper} $out/share/rei-login/wallpaper.jpg

  # niri config for the greeter session. swaybg paints the wallpaper, gtkgreet
  # draws the login card (layer-shell, so it floats over the wallpaper), and
  # niri quits as soon as gtkgreet exits - that is what tells greetd the
  # greeter is done and the real session can start.
  cat > $out/share/rei-login/niri-greeter.kdl <<EOF
  // Generated by flake-rei (login/default.nix) — see README, "Login screen".
  hotkey-overlay {
    skip-at-startup
  }

  spawn-at-startup "sh" "-c" "swaybg -i $out/share/rei-login/wallpaper.jpg -m fill"
  spawn-at-startup "sh" "-c" "gtkgreet -l -s $out/share/rei-login/greeter.css -c niri-session; niri msg action quit"
  EOF
''
